CREATE TABLE Bidder(
   UserID VARCHAR(100) NOT NULL,
   Rating INT NOT NULL,
   Country VARCHAR(100),
   Location VARCHAR(100),
   PRIMARY KEY (UserID)
);

CREATE TABLE Seller(
	UserID VARCHAR(100) NOT NULL,
	Rating INT NOT NULL,
	PRIMARY KEY (UserID)
);

CREATE TABLE Item(
	ItemID INT NOT NULL,
	Name VARCHAR(200) NOT NULL,
	Description VARCHAR(4000) NOT NULL,
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	Currently DECIMAL(8,2) NOT NULL,
	First_Bid DECIMAL(8,2) NOT NULL,
    Buy_Price DECIMAL(8,2) DEFAULT NULL,
    Country VARCHAR(100) NOT NULL,
    Location VARCHAR(100) NOT NULL,
    Latitude VARCHAR(20) DEFAULT NULL,
    Longitude VARCHAR(20) DEFAULT NULL,
	Number_of_Bids INT NOT NULL,
	Seller VARCHAR(75) NOT NULL,
	PRIMARY KEY (ItemID),
	FOREIGN KEY (Seller) REFERENCES Seller(UserID)
);

CREATE TABLE ItemCategory (
	ItemID INT NOT NULL,
	Category VARCHAR(100) NOT NULL,
	PRIMARY KEY (ItemID, Category),
	FOREIGN KEY (ItemID) REFERENCES Item (ItemID)
);


CREATE TABLE Bid(
	UserID VARCHAR(100) NOT NULL,
	ItemID INT NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8,2) NOT NULL,
	PRIMARY KEY (UserID, Time),
	FOREIGN KEY (UserID) REFERENCES Bidder(UserID),
	FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);

